---
- name: Run "apt-get update"
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  changed_when: false
  apt:
    update_cache: yes

- name: Install GNUPG 2
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes
  apt:
    name: gnupg2
    state: latest

- name: Install Unzip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes
  apt:
    name: unzip
    state: latest

- name: Install Build Essentials
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes
  apt:
    name: build-essential
    state: latest

- name: Create Download Directory
  file:
    path: "{{ download_directory }}"
    state: directory
    mode: '0755'

#- name: Install Nix
#  import_task: install_nix.yml

- name: Check that Nix is Installed
  stat:
    path: "{{ nix_install_location }}"
  register: nix_exists

- name: Print that Nix is installed successfully
  debug:
    msg: "Nix successfully installed"
  when: nix_exists.stat.exists and nix_exists.stat.isdir

- name: Print if Nix not installed
  debug:
    msg: "Nix not installed, run installer first."
  when: not nix_exists.stat.exists
